# Generated by Django 5.1.4 on 2025-01-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_id", models.IntegerField()),
                ("checkin_datetime", models.DateTimeField()),
                ("checkin_comment", models.CharField(max_length=999)),
                ("beer_bid", models.IntegerField()),
                ("beer_name", models.CharField(max_length=500)),
                ("beer_abv", models.DecimalField(decimal_places=2, max_digits=4)),
                ("beer_style", models.CharField(max_length=250)),
                ("brewery_id", models.IntegerField()),
                ("brewery_name", models.CharField(max_length=500)),
                ("brewery_country", models.CharField(max_length=250)),
                ("brewery_city", models.CharField(max_length=250)),
                ("brewery_latitude", models.IntegerField()),
                ("brewery_longitude", models.IntegerField()),
                ("venue_id", models.IntegerField()),
                ("venue_name", models.CharField(max_length=500)),
                ("venue_address", models.CharField(max_length=500)),
                ("venue_city", models.CharField(max_length=250)),
                ("venue_country", models.CharField(max_length=250)),
                ("venue_latitude", models.IntegerField()),
                ("venue_longitude", models.IntegerField()),
            ],
        ),
    ]
