# Generated by Django 5.1.4 on 2025-01-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplified_checkins", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Checkin",
            new_name="Checkins",
        ),
    ]
